### PR TITLE
Feature/region callbacks

### PR DESCRIPTION
**Pull request by dagatsoin**
Exposing:
```
mapView:regionWillChangeAnimated:
mapViewRegionIsChanging:
mapView:regionDidChangeAnimated:
```
Usage:
```
void addRegionWillChangeAnimatedCallback(callback: function(LatLng coords));
void addRegionIsChangingCallback(callback: function(LatLng coords));
void addRegionDidChangeAnimatedCallback(callback: function(LatLng coords));
```
Also added three (will, is, did) callbacks which log center coordinates in `index.html`

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Super! I have one remark: those function names are a bit iOS-style and the JS API is supposed to be platform agnostic. If we later add these callback functions to Android as well a more generic name seems appropriate. What are your thoughts about `regionWillChange` instead of `addRegionWillChangeAnimatedCallback`?

**Comment by dagatsoin** [comment]
Ho, good point. I will modify this. Do you think I have to close this PR and reopen it once the commit is done? Or I can leave it open?

**Comment by EddyVerbruggen** [comment]
Cool! No need to close this: you can make additional commits to the fork you created the PR from - they will be added to this PR automatically when you push to your fork.

**Comment by dagatsoin** [comment]
ok done, I also send back camera informations to JS on map changes. (tilt, altitude, heading)

**Comment by EddyVerbruggen** [comment]
Looks great, merged!

**Pull request merged**
